package com.example.order_service;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.util.Date;
import java.util.UUID;

@DynamoDBTable(tableName = "Orders")
public class Order {
    
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String orderId;
    
    @DynamoDBAttribute
    private String customerName;
    
    @DynamoDBAttribute
    private Double orderAmount;
    
    @DynamoDBAttribute
    private String orderDate;
    
    @DynamoDBAttribute
    private String invoiceFileUrl;

    // Constructors
    public Order() {
        this.orderId = UUID.randomUUID().toString();
        this.orderDate = new Date().toString();
    }

    // Getters and Setters
    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public Double getOrderAmount() {
        return orderAmount;
    }

    public void setOrderAmount(Double orderAmount) {
        this.orderAmount = orderAmount;
    }

    public String getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }

    public String getInvoiceFileUrl() {
        return invoiceFileUrl;
    }

    public void setInvoiceFileUrl(String invoiceFileUrl) {
        this.invoiceFileUrl = invoiceFileUrl;
    }
}